# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "*/15 * * * *"

name: Grading-Script

jobs:
  Grading-Script:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install dependencies
        run: |
          install.packages(c("devtools", "jsonlite", "gh"))
          devtools::install_github("jdtrat/simplegit")
        shell: Rscript {0}
      - name: Load Script
        run: |
          source("R/grading_script.R")
        shell: Rscript {0}
      - name: Ping Mason
        run: Rscript -e 'ds4psych_grading("${{ secrets.GITHUB_REPOSITORY}}")'

